### ISSUE TITLE
Widget on a dark background

### ISSUE THREAD

**Issue by pepelsbey** [web-platform-dx/baseline-status#26] opened 2024-10-23 16:42 UTC
I can see the intention of not setting the widget’s background: it blends into your website’s background even when the color scheme switches to light or dark. But I noticed that it breaks terribly when the `<baseline-status>` used on websites that allow forcing a color scheme by setting some class name and remembering it in the `localStorage`.

[Here’s a simplified example](https://codepen.io/pepelsbey/pen/QWeqeVW):

<img width="870" alt="image" src="https://github.com/user-attachments/assets/4cba4b5f-98db-4756-adf5-15fcefa9dbaa">

You can set widget’s `color` to `inherit` and this kind of fixes the issue:

<img width="869" alt="image" src="https://github.com/user-attachments/assets/c16311c1-d94a-400b-8002-f7277de64ea1">

But I’m still not sure if it would work in most cases. The most reliable thing to do would be to set the background.

**Comment by argyleink** [comment] 2024-10-23 17:41
dupe of #10? https://github.com/web-platform-dx/baseline-status/pull/21 was merged to fix it, but maybe it's not deployed?

**Comment by pepelsbey** [comment] 2024-10-23 17:51
I can’t find `light-dark` in the [1.0.7 bundle](https://cdn.jsdelivr.net/npm/baseline-status@1.0.7/baseline-status.min.js). I guess it wasn’t released. But I’m not sure how it’s going to fix the issue: the fix have only reorganized colors in `light-dark` functions. There’s still no background and forced dark background with light color scheme on will result in the same black on black situation.

**Comment by nickautomatic** [comment] 2024-10-23 18:03
I was about to report what I think might be an example of this issue (hence posting in this thread): if I check [this page](https://web.dev/blog/font-size-adjust) on web.dev then I see this:

![image](https://github.com/user-attachments/assets/3073bb9e-2e6f-48b4-a72a-9d6e4e93ebd3)

I believe you should be able to replicate this by setting "**prefers-color-scheme: dark**" in dev tools.

This is linked to from the [launch post](https://web.dev/blog/show-baseline-status) of `baseline-status`, which is how I got to it.

**Comment by pepelsbey** [comment] 2024-10-23 18:11
> #21 was merged to fix it, but maybe it's not deployed?

I see now how it was supposed fix the issue. Unfortunately, it will only work when `color-scheme: light` or `color-scheme: dark` are properly used in the default or forced CSS. But If you do your theming old school way, you’ll end up with black on black or white on white.

**Comment by argyleink** [comment] 2024-10-23 18:27
> Unfortunately, it will only work when `color-scheme: light` or `color-scheme: dark` are properly used in the default or forced CSS. But If you do your theming old school way, you’ll end up with black on black or white on white.

this is true. workaround options? should this widget try and observe old school patterns like `data-theme="dark"` attributes?

**Comment by pepelsbey** [comment] 2024-10-23 18:40
> this is true. workaround options?

I suggested using `color: inherit` instead of the variable on the `:host`. In this case, only icons will be wrong but the text will stay readable.

**Comment by pepelsbey** [comment] 2024-10-24 10:34
![back](https://github.com/user-attachments/assets/0bf05db3-b4a2-47b7-b8c0-cd451f2354cd)

Speaking of the background color that will make this component bulletproof, here’s how we use it on MDN.

It works even better than the version without background: you can clearly tell the status of the feature by the color of the widget without looking at the icon too closely. I think we can feed two birds with one scone here 😉

**Comment by nickautomatic** [comment] 2024-10-24 11:30
> I suggested using `color: inherit` instead of the variable on the `:host`

Fwiw, I think that seems a sensible approach. The problem here seems to be making the foreground color responsive to light/dark theme but not the background color. It seems risky to allow one to be themed but not the other, because it carries an implicit assumption that the context where the component is used will also support light/dark themes, which isn't necessarily the case. In the case of web.dev, for example, there is no dark theme, so flipping the text colour just leads to white-on-white.

**Comment by devnook** [comment] 2024-11-01 12:50
> Speaking of the background color that will make this component bulletproof, here’s how we use a similar component on MDN.
> 
> It works even better than the version without background: you can clearly tell the status of the feature by the color of the widget without looking at the icon too closely. I think we can feed two birds with one scone here 😉

@atopal Wdyt? Can we add background color to the widget based on the baseline value?

**Closed** 2024-11-01 12:57 UTC
